theme = "docuapi"
# themesdir = "../.."
languageCode = "en-us"
baseURL = "https://iani.github.io/sc-hacks-doc"
title = "DocuAPI Example Site"

# deploying on github
publishDir = "docs"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# # Configure the language example tabs.
# # [[params.language_tabs]]
# # key = "go"
# # name = "Go" 
[[params.language_tabs]]
key = "javascript"
name = "SuperCollider"
[[params.language_tabs]]
key = "shell"
name = "Shell" 
[[params.language_tabs]]
key = "emacs-lisp"
name = "emacs-lisp" 
# # [[params.language_tabs]]
# # key = "ruby"
# # name = "Ruby"
# # [[params.language_tabs]]
# # key = "python"
# # name = "Python"


#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "sc-hacks library documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href=\"https://github.com/iani/sc-hacks\">SC-HACKS SOURCE AT GITHUB</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
